### ISSUE TITLE
SET unsafe_enable_version_guessing=true does not work with duckdb 1.1.3

### ISSUE THREAD

**Issue by djouallah** [duckdb/duckdb-iceberg#84]
tried the new update of iceberg extension, unfortunately getting error that SET unsafe_enable_version_guessing=true; is not supported

**Comment by mullinsms** [comment]
@djouallah  you beat me to opening this issue by a whole week!

**Comment by 2blo** [comment]
same

**Comment by naoyak** [comment]
Not sure if this is the cause, but the config option `unsafe_enable_version_guessing` is defined in `Load()` whereas in other extensions it seems to be usually defined in `LoadInternal()`. Maybe @teaguesterling would know from the implementation in #79?

https://github.com/duckdb/duckdb-iceberg/blob/main/src/iceberg_extension.cpp#L30-L39

**Comment by teaguesterling** [comment]
I'm working on a fix for this (as best as I understand it). It's a bit hard to test as I think this only manifests when loading the extension when it's loaded from a different build.

**Comment by teaguesterling** [comment]
I mucked up my dev environment but was able to get it sorted and test this out. @naoyak was right, and this was a simple change. My testing indicates this works, but I am happy to share an unsigned build if anyone else wants to test.
